spring:
  h2.console.enabled: true
  datasource:
    url: ${DB_URL}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

logging:
  level:
    com.example: DEBUG

jwt:
  header: ${JWT_HEADER}
  secret: ${JWT_SECRET_KET}
  token-validity-in-seconds: ${JWT_TOKEN_EXPIRED_SECOND}
